apiVersion: v1
kind: ConfigMap
metadata:
  name: observer-config
data:
  config.conf: |
    status=200
    tick=10s
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vampirs-observer
spec:
  selector:
    matchLabels:
      app: vampirs-observer
  template:
    metadata:
      labels:
        app: vampirs-observer
    spec:
      containers:
      - name: vampirs-observer
        image: brandonrodriguez/vampirs-observer:0.0.3
        #args: ["-config", "/config/config.conf"]  # Pass the -config flag with the file path
        volumeMounts:
        - name: config-volume
          mountPath: /config
          subPath: config.conf
      volumes:
      - name: config-volume
        configMap:
          name: observer-config